// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOW-SRkxE6ovmo9h8Lad3unPKtOzawoDk',
    appId: '1:874865929219:web:120a403d3a9cb610e57236',
    messagingSenderId: '874865929219',
    projectId: 'taka-app-96b9b',
    authDomain: 'taka-app-96b9b.firebaseapp.com',
    storageBucket: 'taka-app-96b9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHQr7SM2_fMT96uJD0B-4yDqF42uOEAW8',
    appId: '1:874865929219:android:0c8719e9876e1a0fe57236',
    messagingSenderId: '874865929219',
    projectId: 'taka-app-96b9b',
    storageBucket: 'taka-app-96b9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKKoeBG9OxDdc0i1y006EapGw0dU8boOA',
    appId: '1:874865929219:ios:88af9fcca1e528b1e57236',
    messagingSenderId: '874865929219',
    projectId: 'taka-app-96b9b',
    storageBucket: 'taka-app-96b9b.appspot.com',
    iosBundleId: 'com.example.mobileProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKKoeBG9OxDdc0i1y006EapGw0dU8boOA',
    appId: '1:874865929219:ios:474f04375f350cc9e57236',
    messagingSenderId: '874865929219',
    projectId: 'taka-app-96b9b',
    storageBucket: 'taka-app-96b9b.appspot.com',
    iosBundleId: 'com.example.mobileProject.RunnerTests',
  );
}
